---

- name: Install build tools
  apt: name=build-essential state=latest update_cache=yes
- name: Install curl
  apt: name=curl state=latest
- name: Install Git
  apt: name=git-core state=latest
# Build CouchDB
- name: Add Erlang Soulutions repository
  apt_repository: repo='deb http://packages.erlang-solutions.com/debian wheezy contrib'
- name: Add key for Erlang Soulutions repository
  apt_key: url=http://binaries.erlang-solutions.com/debian/erlang_solutions.asc state=present
- name: Update apt cache
  apt: update_cache=yes
- name: Install dependencies for CouchDB
  apt: name={{ item }} state=latest
  with_items:
     - erlang-nox
     - erlang-dev
     - libmozjs185-1.0
     - libmozjs185-dev
     - libnspr4
     - libnspr4-0d
     - libnspr4-dev
     - libcurl4-openssl-dev
     - libicu-dev
- name: Set up a couchdb daemon account
  shell: useradd -d /var/lib/couchdb couchdb
- name: Create directories
  shell: sudo mkdir -p /usr/local/lib/couchdb /usr/local/etc/couchdb /usr/local/var/lib/couchdb /usr/local/var/log/couchdb /usr/local/var/run/couchdb /var/lib/couchdb
         && sudo chown -R couchdb:couchdb /usr/local/lib/couchdb /usr/local/etc/couchdb /usr/local/var/lib/couchdb /usr/local/var/log/couchdb /usr/local/var/run/couchdb
         && sudo chmod -R g+rw /usr/local/lib/couchdb /usr/local/etc/couchdb /usr/local/var/lib/couchdb /usr/local/var/log/couchdb /usr/local/var/run/couchdb
- name: Download couchdb sources
  get_url: url=http://apache.volia.net/couchdb/source/1.6.1/apache-couchdb-1.6.1.tar.gz dest=/tmp
- name: Uncompress sources archive
  unarchive: src=/tmp/apache-couchdb-1.6.1.tar.gz dest=/tmp copy=no
- name: Build couchdb from sources
  shell: cd /tmp/apache-couchdb-* && ./configure --prefix=/usr/local --with-js-lib=/usr/lib --with-js-include=/usr/include/mozjs --enable-init
         && make && sudo make install
- name: Start CouchDB
  shell: ln -s /usr/local/etc/init.d/couchdb /etc/init.d/couchdb
         && sudo /etc/init.d/couchdb start
         && sudo update-rc.d couchdb defaults
# Install node.js and required node modules
- name: Add Node.js deb repo
  shell: curl -sL https://deb.nodesource.com/setup | bash -
- name: Install node.js
  apt: name=nodejs state=latest update_cache=yes
- name: Install Coffee-Script
  npm: name=coffee-script global=yes version=1.8.0
- name: Install required Node.js modules
  npm: path=/home/vagrant/proj