---

- name: Install build tools
  apt: name=build-essential state=latest update_cache=yes
- name: Install curl
  apt: name=curl state=latest
- name: Install Git
  apt: name=git-core state=latest
# Install mongodb
- name: Add mongodb public key
  apt_key: keyserver=keyserver.ubuntu.com id=7F0CEB10
- name: Add mongodb repo
  apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/debian-sysvinit dist 10gen' state='present'
- name: Install mongodb
  apt: name=mongodb-org state=latest update_cache=yes
# Install node.js and required node modules
- name: Add Node.js deb repo
  shell: curl -sL https://deb.nodesource.com/setup | bash -
- name: Install node.js
  apt: name=nodejs state=latest update_cache=yes
- name: Install Coffee-Script
  npm: name=coffee-script global=yes version=1.8.0
- name: Install required Node.js modules
  npm: path=/home/vagrant/proj